In [3]:
import tensorflow as tf

In [6]:
## One of the easiest way to create tf.data is using tf.
""""
Steps involved: Creating a tf dataset using sourse daatset. Prprocessing them , ........
"""

'"\nSteps involved: Creating a tf dataset using sourse daatset. Prprocessing them , ........\n'

In [7]:
"""
One of the easiest way of creating tf.data.Dataset is using either tf.data.Dataset.from_tensors and tf.data.Data.from_tensor_slices.
"""

'\nOne of the easiest way of creating tf.data.Dataset is using either tf.data.Dataset.from_tensors and tf.data.Data.from_tensor_slices.\n'

In [21]:
tf_tensor1=tf.constant([1,2,3],dtype=tf.float32)
tf_tensor2=tf.Variable([1,2,3],dtype=tf.float32)

# We use tf.data.Dataset.from_tensors when are are dealing with single element. 

dataset1=tf.data.Dataset.from_tensors(tf_tensor1)
dataset2=tf.data.Dataset.from_tensors(tf_tensor2)

print('Creating tf dataset from tf constant: ',dataset1)
print('Creating tf dataset from tf Variable ',dataset2)

# tf.data.Dataset Object is ia iterator.(Doesn't directly load to memory.). Each item in those iterable are called "element"
print()
for element in dataset1:
    print(element)

Creating tf dataset from tf constant:  <TensorDataset element_spec=TensorSpec(shape=(3,), dtype=tf.float32, name=None)>
Creating tf dataset from tf Variable  <TensorDataset element_spec=TensorSpec(shape=(3,), dtype=tf.float32, name=None)>

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [27]:
## Creating tf dataset from tensor containing more than a element


dataset=tf.data.Dataset.from_tensor_slices(tf.random.normal((4,5)))

print("Creating dataset from tensor having more than a single element : \n", dataset)

for element in dataset:
    print(element)



Creating dataset from tensor having more than a single element : 
 <TensorSliceDataset element_spec=TensorSpec(shape=(5,), dtype=tf.float32, name=None)>
tf.Tensor([ 0.12589556 -0.29566288 -1.4196749   0.19035274  1.0202717 ], shape=(5,), dtype=float32)
tf.Tensor([-0.8924672  -0.6257301  -0.62866145 -0.3998429  -1.3638616 ], shape=(5,), dtype=float32)
tf.Tensor([ 0.4574584  -1.2954105   0.5549091   0.16850777 -0.02755504], shape=(5,), dtype=float32)
tf.Tensor([2.4304144 1.1543106 2.1211581 1.6718373 1.5380313], shape=(5,), dtype=float32)


In [33]:
## Creating dataset from tuple
tuple_data=(1,2,3)
dataset_from_tuple=tf.data.Dataset.from_tensors(tuple_data)


print('The dataset_from_tuple has {} element.'.format(len(dataset_from_tuple)))

for element in dataset_from_tuple:
    print(element)

The dataset_from_tuple has 1 element.
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=3>)


In [40]:


dict_2={'a':1,'b':2} 

dataset_from_dict2=tf.data.Dataset.from_tensors(dict_2) # dict2 is counted as single element.
print("Number of element in dataset_from_dict2 is {}.".format(len(dataset_from_dict2)))

for element in dataset_from_dict2:
    print('element = ',element)
    for value in element.values():
        print(value)

Number of element in dataset_from_dict2 is 1.
element =  {'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=2>}
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [52]:
## Nested tuple()

nested_tuple=(5,('a','b'))
try:
    
    dataset=tf.data.Dataset.from_tensor_slices(nested_tuple)
   
   
except:
    
    dataset=tf.data.Dataset.from_tensors(nested_tuple)
    print("Error: rank > 1 to create tf dataset using from_tensor_slices method ")
    
    


for element in dataset:
    print(element)


print('dataset.as_numpy_iterator(): ', dataset.as_numpy_iterator())


Error: rank > 1 to create tf dataset using from_tensor_slices method 
(<tf.Tensor: shape=(), dtype=int32, numpy=5>, (<tf.Tensor: shape=(), dtype=string, numpy=b'a'>, <tf.Tensor: shape=(), dtype=string, numpy=b'b'>))
dataset.as_numpy_iterator():  <tensorflow.python.data.ops.dataset_ops._NumpyIterator object at 0x00000153DE9B05E0>


In [76]:
## Dataset with both features and labels
f=[[1,2,3],[4,5,6]]
l=[['a'],['b']]
features=tf.data.Dataset.from_tensor_slices(f)
labels=tf.data.Dataset.from_tensor_slices(l)

#

feature_labels=tf.data.Dataset.from_tensor_slices((f,l))

for element_f,element_j in feature_labels:
    print()
    print(element)
    print()
    print(element_f)
    print()
    print(element_j)


(<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 0.03916196, -0.3756081 , -0.04804247,  1.5010437 , -0.3632689 ],
      dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)

tf.Tensor([b'a'], shape=(1,), dtype=string)

(<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 0.03916196, -0.3756081 , -0.04804247,  1.5010437 , -0.3632689 ],
      dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)

tf.Tensor([b'b'], shape=(1,), dtype=string)


In [7]:
## from mnist dataset

train_ds, test_ds=tf.keras.datasets.mnist.load_data()

train_ds=tf.data.Dataset.from_tensor_slices(train_ds)

test_ds=tf.data.Dataset.from_tensor_slices(test_ds)


In [11]:
# Next how to use map here