In this Jupyter notebook, we will learn how to imply a generator for employing tf.data training pipeline.  When do we used it ?
<br>
We use generator method to train large training files save in a local directory.  There are already existing method such as tf.keras "ImageGenerator" which allows us to work directly from the directory. In this turtorial we will also create our own ImageGenerator but using tf.data.Dataset.from_generator().  
<br>
If we already have a predefined method such as tf.keras "ImageGenerator", then why to build such put extra effort to build custom data generator? 
> We may need to work on other type of data such as video or audio which does not have predefined Generator. 

In [1]:
import tensorflow as tf 
from glob import glob 
import os 
from os.path import join,basename,exists




In [ ]:
## Creating Generator Class 

class image_generator:

    def __init__(self,dire,is_training=False):

        self.dire=dire
        self.df=df
        self.is_training=is_training

    def get_labels(self,filename):

        

In [18]:
arr=tf.random.normal((100,),100)

In [24]:
ds=tf.data.Dataset.from_tensor_slices(arr)

In [25]:
ds=ds.batch(5)

: 

tf.Tensor([100.275696  98.76869   99.994896  99.607285  99.88992 ], shape=(5,), dtype=float32)
tf.Tensor([100.77102  99.34119 100.45004  99.3099  100.44538], shape=(5,), dtype=float32)
tf.Tensor([ 99.70236  100.760315  99.852135 100.666275 100.636955], shape=(5,), dtype=float32)
tf.Tensor([ 99.59508   99.13174   99.81141  102.184685  98.865135], shape=(5,), dtype=float32)
tf.Tensor([ 99.97172  101.48699   99.21467   99.312675 100.2843  ], shape=(5,), dtype=float32)
tf.Tensor([ 97.616806 100.76849  101.11101  101.82543  100.458984], shape=(5,), dtype=float32)
tf.Tensor([101.834305 101.041885  98.34062  100.39635  101.027626], shape=(5,), dtype=float32)


In [11]:
ele=ds.take(20)

In [15]:
for element in ds:
    print(ele.numpy())

AttributeError: 'TakeDataset' object has no attribute 'numpy'