In [2]:
import tensorflow as tf 

In [3]:
 ## creatin a simple text tensor

## We can do that by using simple tf.Variable 

str_var=tf.Variable('Hello, how are you?') # We can use sentennce.
print(str_var.numpy())


str_var=tf.Variable('Hello') # We can use single word or char
print(str_var.numpy())


b'Hello, how are you?'
b'Hello'


 We mostly use string Variable in NLP tasks, such as text generation, summarization, classification(sucg as Sentiment Analysis).  Before that we need to learn some preprocessing  for text or string format. 

 - step 1: `Tokenizing`:  Usually, we use string in time-series event. If our input is a char, for example, "hello", then each char {h e l l o} are treated as different sequence of event. Or, if our input is simply a sentence then we can treat each words as different tokens. For example if our input is "Hello world", then we will have two tokens {"Hello", "world"}. In NLP we prefer to use `token` word for representing each sequence.

 - Step 2: `Vectorization or Assigning ID`: Computers only understand number. That means they can't understand "tokens" which are either a char or word or even phrases. So, we will represent each of these tokens with some unique ID. This process of assigning ID is knonw as Vectorization.  There are different way to vectorize a token, and they are:
    1. Assigning `Int` ID:  In this process of vectorization we assign each token with a "int" value.  For example: Orange==> 4, Apple==>5. *Note: This method can't* address the semantic relationship. 

    2. Assigning `array` or `vector` ID:  In this method rather that assigning a 'int' id to a token we will assign then vectors id. There are various method to do this. One of the simple method is `one_hot_encoding()` the "INT" id tokens. However, this method is not good as these vectors are mostly sparse. These methods again may not contain the semantic relation. So, other way of doing it is known as `Embedding.` Unlike `one_hot_encoding` it is not sparse. And each index has some value; you can think of it as output from `softmax`.  For example: Orange==> [0.01,0.002,,0.34, ..........]
    





 

Let us learn how to tokenize string

In [4]:
tf_chars=tf.Variable('Hello')
print('Before tokenizing: ',tf_chars.numpy())

## Now in order to tokenize we need to split each character. Each character are then treated as diffetent tokens itself

Before tokenizing:  b'Hello'


## Vectorizing assigning a unique ID to each token

Here, each of our tokens will be `char`. And we will use 


In [6]:
## First we need to tokenize text from each char, for this tf.strings unicode split
input_text=tf.Variable('hello, wolrd!')
char_token=tf.strings.unicode_split(input_text,input_encoding='UTF-8')
print(char_token.numpy())

[b'h' b'e' b'l' b'l' b'o' b',' b' ' b'w' b'o' b'l' b'r' b'd' b'!']


In [24]:
vocab=['a','b','d','e','f', 'hello']


id_from_char=tf.keras.layers.StringLookup(vocabulary=vocab)


## We can also pront how the vocabular if id_from_char look like 

print(list(id_from_char.get_vocabulary())) ## You will see a certain vocab listed here, '[UNK]' for 0

## So this means any unique character which is not in the voab then it will be 0 indexed. 

ids=id_from_char(char_token)


print(ids.numpy()) ## You can observe that if the char is not available in above vocab then it will simply return 0. And if these character are there then 
#it will return the index of that char in the vocab. 



['[UNK]', 'a', 'b', 'd', 'e', 'f', 'hello']
[0 4 0 0 0 0 0 0 0 0 0 3 0]


In [25]:
vocab=['Hello Sir', 'damn','h'] ## Also the vocab can be string or char or even sentence. Example, Hello Sir ==> index will be 0, and 'h' 


id_from_char=tf.keras.layers.StringLookup(vocabulary=vocab)

## Since the vocab contain both "word" and "char" lets see how the vocab of our id_from_char looks like this time

print(list(id_from_char.get_vocabulary()))

ids=id_from_char(char_token)


print(ids.numpy()) ## You can observe that if the char is not available in above vocab then it will simply return 0. And if these character are there then 
#it will return the index of that char in the vocab. 

['[UNK]', 'Hello Sir', 'damn', 'h']
[3 0 0 0 0 0 0 0 0 0 0 0 0]


In [27]:
vocab = ['Hello Sir', 'damn', 'h']
id_from_char = tf.keras.layers.StringLookup(vocabulary=vocab)
char_token = tf.constant([b'h', b'e', b'l', b'l', b'o', b',', b' ', b'w', b'o', b'l', b'r', b'd', b'!'])
ids = id_from_char(char_token)
print(ids.numpy())  # Should output [4 0 0 0 0 0 0 0 0 0 0 0 0]

[3 0 0 0 0 0 0 0 0 0 0 0 0]


In [29]:
print(ids)

tf.Tensor([3 0 0 0 0 0 0 0 0 0 0 0 0], shape=(13,), dtype=int64)


# Assigning vector like ID (See Embedding above)

