In tensorflow we can expland dimension :
1. tf.expand_dims(tf_tensor,axis=)
2. tf_tensor[tf.newaxis] 

In this notebook we will learn both of these methods

In [41]:
import tensorflow as tf 

Create sample variables

In [42]:
var1=tf.random.normal(shape=(5,)) ## 1 dimensional tensor
var2=tf.random.normal(shape=(2,5)) ## 2 dimensional tensor
var3= tf.random.normal(shape=(100,32,35))

#### expand_dims

In [43]:
tf.expand_dims(var1,axis=0) ## Add a dimension in axis 0 

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[ 0.39163   , -1.2627145 ,  0.21132141, -0.23582977, -1.7173626 ]],
      dtype=float32)>

In [44]:
tf.expand_dims(var1,axis=1) ## add a dimension in axis 1 (Guess the shape before running this cell)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 0.39163   ],
       [-1.2627145 ],
       [ 0.21132141],
       [-0.23582977],
       [-1.7173626 ]], dtype=float32)>

In [45]:
## See the change in 2 dimensional : var2.shape ==> 2,5
tf.expand_dims(var2,axis=0)

<tf.Tensor: shape=(1, 2, 5), dtype=float32, numpy=
array([[[-0.32845423, -0.717312  , -1.0912486 , -0.02161442,
         -0.24046446],
        [-1.3345367 ,  1.4086006 , -0.54044545, -0.7197274 ,
          0.15788426]]], dtype=float32)>

In [46]:
tf.expand_dims(var2,axis=1)

<tf.Tensor: shape=(2, 1, 5), dtype=float32, numpy=
array([[[-0.32845423, -0.717312  , -1.0912486 , -0.02161442,
         -0.24046446]],

       [[-1.3345367 ,  1.4086006 , -0.54044545, -0.7197274 ,
          0.15788426]]], dtype=float32)>

In [47]:
tf.expand_dims(var2,axis=2)

<tf.Tensor: shape=(2, 5, 1), dtype=float32, numpy=
array([[[-0.32845423],
        [-0.717312  ],
        [-1.0912486 ],
        [-0.02161442],
        [-0.24046446]],

       [[-1.3345367 ],
        [ 1.4086006 ],
        [-0.54044545],
        [-0.7197274 ],
        [ 0.15788426]]], dtype=float32)>

In [48]:
## varible 3 ; orginal shape ==> 100,32,35
tf.expand_dims(var3,axis=0)

<tf.Tensor: shape=(1, 100, 32, 35), dtype=float32, numpy=
array([[[[ 2.4925137 , -1.1101848 , -0.82798034, ...,  0.7048373 ,
           1.2185612 , -1.7048306 ],
         [-0.13539194,  0.7534666 ,  1.5282495 , ...,  0.6839043 ,
          -0.60864913, -0.4167018 ],
         [-0.37538385,  2.472861  ,  0.6156966 , ...,  0.75326693,
           1.4831878 , -2.2392168 ],
         ...,
         [-1.1692637 , -0.73177123, -1.3522156 , ...,  0.02238748,
           0.40607193,  0.32871333],
         [ 0.1835674 , -1.0082026 ,  0.54896134, ...,  0.04370227,
           1.0571452 , -0.17936547],
         [ 0.43974367, -0.08315629,  1.6176492 , ...,  0.01482289,
          -0.34774858, -1.4671348 ]],

        [[ 0.4610109 , -0.84694403, -0.32067224, ..., -1.5154301 ,
          -0.20123681,  0.07532458],
         [ 0.7262406 ,  0.10636365,  1.1210077 , ..., -0.19983707,
           0.23408093,  0.16879743],
         [-1.3047909 ,  0.9294069 ,  0.25833878, ...,  1.244512  ,
           1.5167873 , -0.1

In [49]:
tf.expand_dims(var3,axis=3) ## Add dimension in last axis

<tf.Tensor: shape=(100, 32, 35, 1), dtype=float32, numpy=
array([[[[ 2.4925137 ],
         [-1.1101848 ],
         [-0.82798034],
         ...,
         [ 0.7048373 ],
         [ 1.2185612 ],
         [-1.7048306 ]],

        [[-0.13539194],
         [ 0.7534666 ],
         [ 1.5282495 ],
         ...,
         [ 0.6839043 ],
         [-0.60864913],
         [-0.4167018 ]],

        [[-0.37538385],
         [ 2.472861  ],
         [ 0.6156966 ],
         ...,
         [ 0.75326693],
         [ 1.4831878 ],
         [-2.2392168 ]],

        ...,

        [[-1.1692637 ],
         [-0.73177123],
         [-1.3522156 ],
         ...,
         [ 0.02238748],
         [ 0.40607193],
         [ 0.32871333]],

        [[ 0.1835674 ],
         [-1.0082026 ],
         [ 0.54896134],
         ...,
         [ 0.04370227],
         [ 1.0571452 ],
         [-0.17936547]],

        [[ 0.43974367],
         [-0.08315629],
         [ 1.6176492 ],
         ...,
         [ 0.01482289],
         [-0.34774

 Explanding with tf.newaxis

In [50]:
# var1 shape=> 5
var1[tf.newaxis] ## if no slicing is given add a dims at axis =1

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[ 0.39163   , -1.2627145 ,  0.21132141, -0.23582977, -1.7173626 ]],
      dtype=float32)>

In [51]:
var1[tf.newaxis,:] ## same as above(add dimension at axis =0, and leave other same)

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[ 0.39163   , -1.2627145 ,  0.21132141, -0.23582977, -1.7173626 ]],
      dtype=float32)>

In [52]:
var1[:,tf.newaxis] ## Add dimension at the end 

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 0.39163   ],
       [-1.2627145 ],
       [ 0.21132141],
       [-0.23582977],
       [-1.7173626 ]], dtype=float32)>

In [53]:
##with var2; original shape ==> 2,5
var2[tf.newaxis]

<tf.Tensor: shape=(1, 2, 5), dtype=float32, numpy=
array([[[-0.32845423, -0.717312  , -1.0912486 , -0.02161442,
         -0.24046446],
        [-1.3345367 ,  1.4086006 , -0.54044545, -0.7197274 ,
          0.15788426]]], dtype=float32)>

In [54]:
var2[tf.newaxis,:,:]

<tf.Tensor: shape=(1, 2, 5), dtype=float32, numpy=
array([[[-0.32845423, -0.717312  , -1.0912486 , -0.02161442,
         -0.24046446],
        [-1.3345367 ,  1.4086006 , -0.54044545, -0.7197274 ,
          0.15788426]]], dtype=float32)>

In [55]:
var2[:,tf.newaxis,:] ## So similar to tf.expand_dims. use slicing, add new tf.newaxis in that axis where you want to expand axs

<tf.Tensor: shape=(2, 1, 5), dtype=float32, numpy=
array([[[-0.32845423, -0.717312  , -1.0912486 , -0.02161442,
         -0.24046446]],

       [[-1.3345367 ,  1.4086006 , -0.54044545, -0.7197274 ,
          0.15788426]]], dtype=float32)>

In [56]:
# I can also tf.newxis multiple times; this makes it simple to use
# for example you have a image with 2 dimension; h,w; since you want to train it you have to add batch size as well as channel=1
h,w=480,640
img_var=tf.random.normal(shape=(h,w))
## In order to predict the result from cnn model it should have batch size(new axis at 0) as well as channel(new axis at end)

img_var[tf.newaxis,:,:,tf.newaxis] ##  batchs_size,h,w,c; One liner solutions

<tf.Tensor: shape=(1, 480, 640, 1), dtype=float32, numpy=
array([[[[-1.4382564 ],
         [ 0.3823777 ],
         [-0.032017  ],
         ...,
         [-0.7965839 ],
         [ 0.06284888],
         [ 1.9984078 ]],

        [[-0.73454666],
         [-0.6723347 ],
         [-0.15401179],
         ...,
         [ 0.32628876],
         [ 0.2669377 ],
         [ 0.07488581]],

        [[ 0.60368776],
         [ 0.37556434],
         [ 0.17193413],
         ...,
         [-0.30077058],
         [-0.89738923],
         [ 0.8910382 ]],

        ...,

        [[ 0.6005567 ],
         [-0.9261451 ],
         [-0.62131315],
         ...,
         [ 1.4078816 ],
         [ 0.52655846],
         [-0.36396974]],

        [[-0.28684464],
         [ 0.4370538 ],
         [-1.5343621 ],
         ...,
         [ 2.443767  ],
         [-0.8071059 ],
         [-0.44976777]],

        [[-1.1381974 ],
         [ 0.34928584],
         [-2.292578  ],
         ...,
         [ 1.804529  ],
         [ 1.00743

## squeeze
This operation is useful to reduce dimension with value 1. It can be useful to remove the batch axis . Two ways to do it:
- tf.squeeze
- tensorflow slicing

In [58]:
expanded_var=img_var[tf.newaxis,:,:,tf.newaxis]

In [60]:
## squeenze or unexpand

reduced_batch=tf.squeeze(expanded_var,axis=0)
red_to_img=tf.squeeze(reduced_batch,axis=2)

In [61]:
red_to_img

<tf.Tensor: shape=(480, 640), dtype=float32, numpy=
array([[-1.4382564 ,  0.3823777 , -0.032017  , ..., -0.7965839 ,
         0.06284888,  1.9984078 ],
       [-0.73454666, -0.6723347 , -0.15401179, ...,  0.32628876,
         0.2669377 ,  0.07488581],
       [ 0.60368776,  0.37556434,  0.17193413, ..., -0.30077058,
        -0.89738923,  0.8910382 ],
       ...,
       [ 0.6005567 , -0.9261451 , -0.62131315, ...,  1.4078816 ,
         0.52655846, -0.36396974],
       [-0.28684464,  0.4370538 , -1.5343621 , ...,  2.443767  ,
        -0.8071059 , -0.44976777],
       [-1.1381974 ,  0.34928584, -2.292578  , ...,  1.804529  ,
         1.0074383 , -1.1771523 ]], dtype=float32)>

In [63]:
## using slicing (one liner)

expanded_var[0,:,:,0] ## Put 0 to those where you want to reduce dimension 

<tf.Tensor: shape=(480, 640), dtype=float32, numpy=
array([[-1.4382564 ,  0.3823777 , -0.032017  , ..., -0.7965839 ,
         0.06284888,  1.9984078 ],
       [-0.73454666, -0.6723347 , -0.15401179, ...,  0.32628876,
         0.2669377 ,  0.07488581],
       [ 0.60368776,  0.37556434,  0.17193413, ..., -0.30077058,
        -0.89738923,  0.8910382 ],
       ...,
       [ 0.6005567 , -0.9261451 , -0.62131315, ...,  1.4078816 ,
         0.52655846, -0.36396974],
       [-0.28684464,  0.4370538 , -1.5343621 , ...,  2.443767  ,
        -0.8071059 , -0.44976777],
       [-1.1381974 ,  0.34928584, -2.292578  , ...,  1.804529  ,
         1.0074383 , -1.1771523 ]], dtype=float32)>