**stack operation**: gathers a list of tensors and stacks them along a ``new axis``, creating a new dimension. We will also learn how ``stack and concat`` are not the same.

**Unstack Operation**: splits a tensor into a list of tensors along the specified axis. The number of resulting tensors will be equal to the size of the dimension at the specified axis.

In [50]:
import tensorflow as tf 

In [51]:
var1=tf.ones(shape=(5,))
var2=tf.zeros(shape=(5,))

var3=tf.random.normal(shape=(3,5))
var4=tf.random.normal(shape=(3,5))


In [52]:
tf.stack([var1,var2],axis=0) ## Default is axis 0


<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [53]:
tf.stack([var1,var2],axis=1) ## In axis =1

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)>

In [54]:
stacked0=tf.stack([var3,var4],axis=0) 


In [55]:
stacked1=tf.stack([var3,var4],axis=1) 


In [56]:
stacked2=tf.stack([var3,var4],axis=2) 

In [57]:
stacked1

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[ 0.24069211, -0.1446253 , -0.71781075, -0.681972  ,
         -0.43706462],
        [ 0.05850146, -0.17731702,  2.1237292 , -1.5222365 ,
          0.9632891 ]],

       [[-1.9542998 ,  0.10636945, -0.03422093, -0.4193867 ,
         -0.51660067],
        [-0.12904885,  0.4992137 ,  0.01568054, -0.00931948,
          1.0841675 ]],

       [[-1.0968574 , -0.766838  , -0.46020246,  0.9222632 ,
         -2.433876  ],
        [ 0.05320054, -0.66009384,  1.2177445 ,  1.0913743 ,
         -0.2334003 ]]], dtype=float32)>

In [58]:
stacked0[0]==var3

<tf.Tensor: shape=(3, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [35]:
stacked1[:,0,:]==var3

<tf.Tensor: shape=(3, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

is stacking same as concatenate? 
==> Answer is No. Concatenate gathers tensor in `existing` axis not new `axis`

==> in tf.concat, we can set axis(from exising shape only) (num of dim don't change) 

In [11]:
tf.concat([var1,var2],axis=0) ## you see that concat is done 

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.], dtype=float32)>

In [36]:
#tf.concat([var1,var2],axis=1) ; give error coz both var1 and var2

In [37]:
tf.concat([var3,var4],axis=0)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[ 0.36593318,  2.2156844 , -0.03587857,  0.57105696, -0.93334293],
       [ 0.07200411,  0.50055546, -1.6158595 , -1.2536744 ,  1.6761937 ],
       [ 0.06026825, -0.36437926, -0.24018605, -0.01017379,  0.8560304 ],
       [ 0.20520672, -1.7214019 , -0.20540515, -1.2079625 , -0.8156779 ],
       [ 0.0633375 , -0.8792992 , -0.14642236, -0.9597081 , -0.9596648 ],
       [ 0.18855019, -0.19273683, -1.4876363 ,  3.5991538 ,  0.49772814]],
      dtype=float32)>

In [38]:
tf.concat([var3,var4],axis=1)

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[ 0.36593318,  2.2156844 , -0.03587857,  0.57105696, -0.93334293,
         0.20520672, -1.7214019 , -0.20540515, -1.2079625 , -0.8156779 ],
       [ 0.07200411,  0.50055546, -1.6158595 , -1.2536744 ,  1.6761937 ,
         0.0633375 , -0.8792992 , -0.14642236, -0.9597081 , -0.9596648 ],
       [ 0.06026825, -0.36437926, -0.24018605, -0.01017379,  0.8560304 ,
         0.18855019, -0.19273683, -1.4876363 ,  3.5991538 ,  0.49772814]],
      dtype=float32)>

Testing on tensor which have only one dimension of same size

In [39]:
var5=tf.random.normal(shape=(3,5))
var6=tf.random.normal(shape=(3,10))

In [42]:
##tf.stack([var5,var6]) won't run because both of the dimension should match; need to have exact shape

In [47]:
## We have same num of row; so we can concatenate on axis=1;
#because in concat if i want to concat on axis=1 (then other axis in thois case axis_0 meust be same)

In [48]:
tf.concat([var5,var6],axis=1)

<tf.Tensor: shape=(3, 15), dtype=float32, numpy=
array([[ 0.78171724, -1.3166919 ,  0.37393576,  1.1073192 , -1.0791205 ,
         0.15733165,  1.9752271 ,  2.251921  ,  1.0065525 , -0.24835645,
        -0.7208744 ,  1.4292198 ,  0.80064845, -0.7713076 ,  0.34154668],
       [ 0.51475495,  1.4621357 , -0.05029101,  0.32891813, -0.5457578 ,
        -0.5083453 , -0.96762943, -0.878308  , -0.38614368, -0.6331209 ,
        -0.49577576,  1.5420189 , -0.08993945,  0.04970931, -0.17508204],
       [ 0.7992061 ,  0.3699602 , -0.3793552 ,  0.30531013, -0.39434952,
        -1.3624943 , -0.98038715,  0.06446909, -0.14021477,  0.7402125 ,
         0.27491698, -0.54070544, -2.0872989 , -0.16820636, -2.2675383 ]],
      dtype=float32)>

### unstack

==> return a list of unstacked tensors

In [62]:
print('stacked0 shape ', stacked0.shape)
unstack=tf.unstack(stacked0,axis=0)

for tensor in unstack:
    print('unstacked tensor shape ', tensor.shape)

stacked0 shape  (2, 3, 5)
unstacked tensor shape  (3, 5)
unstacked tensor shape  (3, 5)


In [63]:
var=tf.random.normal(shape=(2,32,17)) # batch, token,embed_dim

In [64]:
for tensor in tf.unstack(var,axis=0):
    print(tensor.shape)

(32, 17)
(32, 17)
