## Tensors
> Tensors are multi-dimensional arrays. <br> Tensors are immutable

In [1]:
import tensorflow as tf
tf.get_logger().setLevel(3) ## Disable printing information and warning
import numpy as np

2022-10-01 20:06:29.906285: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-01 20:06:29.978544: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-10-01 20:06:29.996737: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-01 20:06:30.379491: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: li

### Creating Basic Tensors
>"scaler"=="rank-o" tensor <br> "vector" == "rank-1" tensor <br>  "matrix"=="rank-2" tensor


In [2]:
## Creating rank_0 tensor
rank_0_tensor=tf.constant(4) ## by default the dtype used is tf.int32
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


2022-10-01 20:06:30.902733: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-01 20:06:30.920678: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-01 20:06:30.920803: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-01 20:06:30.921693: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compi

In [3]:
## Creating rank_1 Tensor
rank_1_tensor=tf.constant([1,2,3,4],dtype=tf.float32) 
print(rank_1_tensor)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [4]:
## Creating rank 2 Tensor 
rank_2_tensor=tf.constant([[1,2],[3,4]])
print(rank_2_tensor)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Basic math operation using tf.Tensor

In [5]:
a=tf.constant([[1,2],[3,4]],dtype=tf.float32)
b=tf.ones([2,2])

In [7]:

print(tf.add(a,b)) ##addition
print(tf.multiply(a,b)) ## element wise multiplication


tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [19]:
x=[[1.,2.,3.]]
w=tf.constant([[1.,2.],[3.,4.],[5.,6.]])


### Tensors are used in all kinds of operations (or "Ops").

In [17]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])


In [18]:
### Performing above method on specific axis
print('a={}'.format(a))
print(tf.reduce_sum(a,axis=0)) ## axis determine perform sum on which axis. axis =0 means perform sum along height or rows

a=[[1. 2.]
 [3. 4.]]
tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [55]:
### Converting to Tensor
print(tf.convert_to_tensor([1,2,3]))
print(tf.convert_to_tensor(np.ones(2))) ## as np.ones() is default np.float64 created tensor is also tf.float64

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1. 1.], shape=(2,), dtype=float64)


In [57]:
### Getting the shape of the Tensor
print('a.shape: ',a.shape)


a.shape:  (2, 2)


### Broadcasting
> What happens when we do mathematical operation with different shape?

In [66]:
c=tf.ones([1,3])*3
d=tf.ones([1])*5
e=tf.constant([1.,4.,5.,6.,8.])
print('c: ',c)
print('d: ',d)
print('e: ',e)
print('c*d: ,',tf.multiply(c,d))
print('c*e : ',tf.multiply(d,e))



c:  tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
d:  tf.Tensor([5.], shape=(1,), dtype=float32)
e:  tf.Tensor([1. 4. 5. 6. 8.], shape=(5,), dtype=float32)
c*d: , tf.Tensor([[15. 15. 15.]], shape=(1, 3), dtype=float32)
c*e :  tf.Tensor([ 5. 20. 25. 30. 40.], shape=(5,), dtype=float32)


In [69]:
#Reshaping
print(tf.reshape(a,(-1,2))) ## Similar as np operation

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


### String Tensor
>Used in NLP tasks

In [72]:
string_tensor=tf.constant(['Hey','Hi','Namaste'])
print(string_tensor)

tf.Tensor([b'Hey' b'Hi' b'Namaste'], shape=(3,), dtype=string)


In [73]:
## Splitting the string_tensor like sting dtype
print(tf.strings.split(string_tensor,sep=" "))

<tf.RaggedTensor [[b'Hey'],
 [b'Hi'],
 [b'Namaste']]>
