## Tensors
> Tensors are multi-dimensional arrays. <br> Tensors are immutable

In [21]:
import tensorflow as tf
tf.get_logger().setLevel(3) ## Disable printing information and warning
import numpy as np

### Creating Basic Tensors
>"scaler"=="rank-o" tensor <br> "vector" == "rank-1" tensor <br>  "matrix"=="rank-2" tensor


In [5]:
## Creating rank_0 tensor
rank_0_tensor=tf.constant(4) ## by default the dtype used is tf.int32
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
## Creating rank_1 Tensor
rank_1_tensor=tf.constant([1,2,3,4],dtype=tf.float32) 
print(rank_1_tensor)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [7]:
## Creating rank 2 Tensor 
rank_2_tensor=tf.constant([[1,2],[3,4]])
print(rank_2_tensor)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Basic math operation using tf.Tensor

In [34]:
a=tf.constant([[1,2],[3,4]],dtype=tf.float32)
b=tf.ones([2,2])

In [35]:

print(tf.add(a,b)) ##addition
print(tf.multiply(a,b)) ## element wise multiplication
print(tf.matmul(a,b)) ##matrix multiplication


tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32)


### Tensors are used in all kinds of operations (or "Ops").

In [36]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])


In [45]:
print('a={}'.format(a))
test=tf.reduce_max(a) ## gives the maximum value of the Tensor
print(test)
print('tf.argmax():',tf.argmax(a)) ## gives the index with max value
print('softmax operation:',tf.nn.softmax(a))



a=[[1. 2.]
 [3. 4.]]
tf.Tensor(4.0, shape=(), dtype=float32)
tf.argmax(): tf.Tensor([1 1], shape=(2,), dtype=int64)
softmax operation: tf.Tensor(
[[0.26894143 0.73105854]
 [0.26894143 0.73105854]], shape=(2, 2), dtype=float32)


In [49]:
### Performing above method on specific axis
print('a={}'.format(a))
print(tf.reduce_sum(a,axis=0)) ## axis determine perform sum on which axis. axis =0 means perform sum along height or rows

a=[[1. 2.]
 [3. 4.]]
tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [55]:
### Converting to Tensor
print(tf.convert_to_tensor([1,2,3]))
print(tf.convert_to_tensor(np.ones(2))) ## as np.ones() is default np.float64 created tensor is also tf.float64

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1. 1.], shape=(2,), dtype=float64)


In [57]:
### Getting the shape of the Tensor
print('a.shape: ',a.shape)


a.shape:  (2, 2)


### Broadcasting
> What happens when we do mathematical operation with different shape?

In [66]:
c=tf.ones([1,3])*3
d=tf.ones([1])*5
e=tf.constant([1.,4.,5.,6.,8.])
print('c: ',c)
print('d: ',d)
print('e: ',e)
print('c*d: ,',tf.multiply(c,d))
print('c*e : ',tf.multiply(d,e))



c:  tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
d:  tf.Tensor([5.], shape=(1,), dtype=float32)
e:  tf.Tensor([1. 4. 5. 6. 8.], shape=(5,), dtype=float32)
c*d: , tf.Tensor([[15. 15. 15.]], shape=(1, 3), dtype=float32)
c*e :  tf.Tensor([ 5. 20. 25. 30. 40.], shape=(5,), dtype=float32)


In [69]:
#Reshaping
print(tf.reshape(a,(-1,2))) ## Similar as np operation

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


### String Tensor
>Used in NLP tasks

In [72]:
string_tensor=tf.constant(['Hey','Hi','Namaste'])
print(string_tensor)

tf.Tensor([b'Hey' b'Hi' b'Namaste'], shape=(3,), dtype=string)


In [73]:
## Splitting the string_tensor like sting dtype
print(tf.strings.split(string_tensor,sep=" "))

<tf.RaggedTensor [[b'Hey'],
 [b'Hi'],
 [b'Namaste']]>
