In [1]:
import tensorflow as tf 
import numpy as np 

In [10]:
## Creating Tensors 

a = tf.constant([[1,2,3]],dtype=tf.int16)
b=tf.constant(tf.zeros(5))
c=tf.constant(tf.random.normal((2,2)))


In [11]:
a=tf.Variable([1,21,3],dtype=tf.float16)


In [27]:
w=tf.Variable(tf.random.normal(shape=(2,2)),dtype=tf.float32)
x=tf.Variable([[1,2]],dtype=tf.float32)

In [28]:
y_pred=tf.nn.softmax(tf.multiply)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.8391539 , -0.95008296],
       [-2.8137786 , -0.5797203 ]], dtype=float32)>

In [35]:
with tf.GradientTape() as tape:
    w=tf.Variable(tf.random.normal(shape=(2,2)),dtype=tf.float32)
    x=tf.Variable([[1,2]],dtype=tf.float32)
    y_pred=tf.nn.softmax(tf.multiply(w,tf.transpose(x)))

grad=tape.gradient(y_pred,[w,x])

In [37]:
grad[1]

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [40]:
with tf.GradientTape(watch_accessed_variables=False) as tape:
    w=tf.Variable(tf.random.normal(shape=(2,2)),dtype=tf.float32)
    x=tf.Variable([[1,2]],dtype=tf.float32)
    tape.watch(w)
    y_pred=tf.nn.softmax(tf.multiply(w,tf.transpose(x)))

grad=tape.gradient(y_pred,[w,x])

In [41]:
tf.keras.save

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 None]

In [120]:
## Lets try to train a simple Linear Model using Tensorflow 

x=tf.Variable(tf.linspace(-2,2,201))
x=tf.cast(x,tf.float16)
true_W=tf.Variable(3,dtype=tf.float16)
true_b=tf.Variable(2,dtype=tf.float16)

print(true_W.shape)
print(x.shape)
y=tf.multiply(x,true_W)+true_b

y_true=y+tf.random.normal(shape=(201,),dtype=tf.float16)


()
(201,)


In [129]:
class simple_dense_layer(tf.keras.layers.Layer):

    def __init__(self,dense_unit):
        super(simple_dense_layer,self).__init__()
        
        self.units=dense_unit
        self.w=tf.Variable(3,dtype=tf.float32)
       
        self.b=tf.Variable(2,dtype=tf.float32)
    
  


    def call(self,x):

        
        print('self.w.shape : ', self.w.shape)
        print('x.shape : ', x.shape)
        print('b.shape : ', self.b.shape)
        z=tf.multiply(self.w,x)+self.b

        return tf.nn.relu(z)

In [130]:
x=tf.Variable(tf.linspace(-2,2,201))
x=tf.cast(x,tf.float16)

In [131]:
x

<tf.Tensor: shape=(201,), dtype=float16, numpy=
array([-2.  , -1.98, -1.96, -1.94, -1.92, -1.9 , -1.88, -1.86, -1.84,
       -1.82, -1.8 , -1.78, -1.76, -1.74, -1.72, -1.7 , -1.68, -1.66,
       -1.64, -1.62, -1.6 , -1.58, -1.56, -1.54, -1.52, -1.5 , -1.48,
       -1.46, -1.44, -1.42, -1.4 , -1.38, -1.36, -1.34, -1.32, -1.3 ,
       -1.28, -1.26, -1.24, -1.22, -1.2 , -1.18, -1.16, -1.14, -1.12,
       -1.1 , -1.08, -1.06, -1.04, -1.02, -1.  , -0.98, -0.96, -0.94,
       -0.92, -0.9 , -0.88, -0.86, -0.84, -0.82, -0.8 , -0.78, -0.76,
       -0.74, -0.72, -0.7 , -0.68, -0.66, -0.64, -0.62, -0.6 , -0.58,
       -0.56, -0.54, -0.52, -0.5 , -0.48, -0.46, -0.44, -0.42, -0.4 ,
       -0.38, -0.36, -0.34, -0.32, -0.3 , -0.28, -0.26, -0.24, -0.22,
       -0.2 , -0.18, -0.16, -0.14, -0.12, -0.1 , -0.08, -0.06, -0.04,
       -0.02,  0.  ,  0.02,  0.04,  0.06,  0.08,  0.1 ,  0.12,  0.14,
        0.16,  0.18,  0.2 ,  0.22,  0.24,  0.26,  0.28,  0.3 ,  0.32,
        0.34,  0.36,  0.38,  0.4 ,  0.42, 

In [132]:
s=simple_dense_layer(201)

In [133]:
s(x)


self.w.shape :  ()
x.shape :  (201,)
b.shape :  ()


<tf.Tensor: shape=(201,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.01953125, 0.07958984, 0.13964844,
       0.19970

In [107]:
x+tf.Variable(3,dtype=tf.float16)

<tf.Tensor: shape=(201,), dtype=float16, numpy=
array([1.   , 1.02 , 1.04 , 1.06 , 1.08 , 1.1  , 1.12 , 1.14 , 1.16 ,
       1.18 , 1.2  , 1.22 , 1.24 , 1.26 , 1.28 , 1.3  , 1.32 , 1.34 ,
       1.36 , 1.38 , 1.4  , 1.42 , 1.44 , 1.46 , 1.48 , 1.5  , 1.52 ,
       1.54 , 1.56 , 1.58 , 1.6  , 1.62 , 1.64 , 1.66 , 1.68 , 1.7  ,
       1.72 , 1.74 , 1.76 , 1.78 , 1.8  , 1.82 , 1.84 , 1.86 , 1.88 ,
       1.9  , 1.92 , 1.94 , 1.96 , 1.98 , 2.   , 2.02 , 2.04 , 2.06 ,
       2.08 , 2.1  , 2.121, 2.14 , 2.16 , 2.18 , 2.2  , 2.22 , 2.24 ,
       2.26 , 2.28 , 2.3  , 2.32 , 2.34 , 2.36 , 2.379, 2.4  , 2.42 ,
       2.44 , 2.46 , 2.48 , 2.5  , 2.52 , 2.54 , 2.56 , 2.58 , 2.6  ,
       2.621, 2.64 , 2.66 , 2.68 , 2.7  , 2.72 , 2.74 , 2.76 , 2.78 ,
       2.8  , 2.82 , 2.84 , 2.86 , 2.88 , 2.9  , 2.92 , 2.94 , 2.96 ,
       2.98 , 3.   , 3.02 , 3.04 , 3.06 , 3.08 , 3.1  , 3.12 , 3.14 ,
       3.16 , 3.18 , 3.2  , 3.22 , 3.24 , 3.26 , 3.28 , 3.3  , 3.32 ,
       3.34 , 3.36 , 3.379, 3.4  , 3.42 , 

In [136]:
class SimpleDenseLayer(tf.keras.layers.Layer):
    def __init__(self, dense_unit):
        super(SimpleDenseLayer, self).__init__()
        self.units = dense_unit
        self.w = tf.Variable(tf.cast(3, tf.float16))
        self.b = tf.Variable(tf.cast(2, tf.float16))

    def call(self, x):

        print('self.w.shape:', self.w.shape)
        print('x.shape:', x.dtype)
        print('b.shape:', self.b.shape)
        z = tf.cast(tf.multiply(self.w, x),tf.float16) + self.b
        return tf.nn.relu(z)

x = tf.Variable(tf.linspace(-2, 2, 201))
x = tf.cast(x, tf.float16)

s = SimpleDenseLayer(201)
s(x)


self.w.shape: ()
x.shape: <dtype: 'float32'>
b.shape: ()


InvalidArgumentError: Exception encountered when calling layer "simple_dense_layer_21" "                 f"(type SimpleDenseLayer).

cannot compute Mul as input #1(zero-based) was expected to be a half tensor but is a float tensor [Op:Mul]

Call arguments received by layer "simple_dense_layer_21" "                 f"(type SimpleDenseLayer):
  • x=tf.Tensor(shape=(201,), dtype=float32)

In [139]:
tf.Variable(tf.random.normal(shape=(5,)),dtype=tf.float16)

ValueError: initial_value: Tensor conversion requested dtype float16 for Tensor with dtype float32: <tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 2.0861773 , -0.94139785, -0.6804789 , -0.90974563, -0.34620494],
      dtype=float32)>

In [141]:
np.array([1,2,3])*np.array(5)

array([ 5, 10, 15])