## Variables
>Variables are created and tracked via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor. Higher level libraries like tf.keras use tf.Variable to store model parameters. <br> variables are mostly used for training parameters as they are capable of differentiation.




In [16]:
import tensorflow as tf

### Creating a variable
>To create a variable, provide an initial value. The tf.Variable will have the same dtype as the initialization value.

In [17]:
a=tf.constant([1,2,3])
v=tf.Variable(a)
print('a: ',a)
print('b: ',v)



a:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
b:  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


### Assigning new value to the exisitng variables
>var.assign([New value])

In [18]:
print('Before assigning new value')
print('v: ',v)
print('After assigning new value :')
v.assign([5,1,3])
print('v: ',v)

Before assigning new value
v:  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
After assigning new value :
v:  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 1, 3], dtype=int32)>


In [19]:
## Creating variables from existing variables. Here two variables will not share the same memory location. 
v1=tf.Variable(v)
print(v1)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 1, 3], dtype=int32)>


>Although variables are important for differentiation, some variables will not need to be differentiated. You can turn off gradients for a variable by setting trainable to false at creation. An example of a variable that would not need gradients is a training step counter. An example of this is: <br> step_counter = tf.Variable(1, trainable=False)

### Naming of the Variables
>Two variables may have same name but still does not share the same memory location

In [27]:
a=tf.Variable(2,name='x')
b=tf.Variable(3,name='x')
(a == b).numpy()

False

### Placing variables and tensors
For better performance, TensorFlow will attempt to place tensors and variables on the fastest device compatible with its dtype. This means most variables are placed on a GPU if one is available.

However, you can override this. In this snippet, place a float tensor and a variable on the CPU, even if a GPU is available. By turning on device placement logging (see Setup), you can see where the variable is placed.

In [47]:
with tf.device('cpu'):
    a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [48]:
with tf.device('cpu'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.Variable([[1.0, 2.0, 3.0]])

with tf.device('gpu'):
  # Element-wise multiply
  k = a*b
  k1=tf.multiply(a,b)
  

print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)
