## Variables
>Variables are created and tracked via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor. Higher level libraries like tf.keras use tf.Variable to store model parameters. <br> variables are mostly used for training parameters as they are capable of differentiation.




In [8]:
import tensorflow as tf

### Creating a variable
>To create a variable, provide an initial value. The tf.Variable will have the same dtype as the initialization value.

In [2]:
a=tf.constant([1,2,3])
v=tf.Variable(a)
print('a: ',a)
print('b: ',v)



a:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
b:  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>


### Assigning new value to the exisitng variables
>var.assign([New value])

In [3]:
print('Before assigning new value')
print('v: ',v)
print('After assigning new value :')
v.assign([5,1,3])
print('v: ',v)

Before assigning new value
v:  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
After assigning new value :
v:  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 1, 3])>


In [4]:
## Creating variables from existing variables. Here two variables will not share the same memory location. 
v1=tf.Variable(v)
print(v1)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 1, 3])>


>Although variables are important for differentiation, some variables will not need to be differentiated. You can turn off gradients for a variable by setting trainable to false at creation. An example of a variable that would not need gradients is a training step counter. An example of this is: <br> step_counter = tf.Variable(1, trainable=False)

### Naming of the Variables
>Two variables may have same name but still does not share the same memory location

In [5]:
a=tf.Variable(2,name='x')
b=tf.Variable(3,name='x')
(a == b).numpy()

False

### Placing variables and tensors
For better performance, TensorFlow will attempt to place tensors and variables on the fastest device compatible with its dtype. This means most variables are placed on a GPU if one is available.

However, you can override this. In this snippet, place a float tensor and a variable on the CPU, even if a GPU is available. By turning on device placement logging (see Setup), you can see where the variable is placed.

In [6]:
with tf.device('cpu'):
    a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [7]:
with tf.device('cpu'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.Variable([[1.0, 2.0, 3.0]])

with tf.device('gpu'):
  # Element-wise multiply
  k = a*b
  k1=tf.multiply(a,b)
  

print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)


tf.cast() Vs dtype 'argument' of tf.Variable(,dtype=). If the objects (may be tensors) we are trying to make tf Variables already have  tf dtypes then we can't use the argument dtype. For example, tf.linspace() return tf.float64; so if we try to convert to tf.float16 the we will get error. One of the way to handle this kind of scenario is to use "tf.cast()".  So, we will use dtype mostly in those cases where the tensor array already does not have a specific tf dtype. For example; tf.Variable(5), here "5" does not have tf dtype. So, if we don't mention any dtype it will take dtype with int as 5 was a integer. However, 5 itself does not have a specific dtype we can use "dtype" argument to change to any other dtype. 

In [13]:
## Example


print('dtype returned : ', tf.linspace(-1,1,10).dtype)

"""
From, the above example we see that tf.linspace() return dtype with float64; Now let us try to make variable from it with dtype float16
"""

try:
    x=tf.Variable(tf.linspace(-1,1,10),dtype=tf.float16)
    
except:
    print("'dtype' arg is tf.Variable can't be used to convert to other data type when the tensor already have its own specific tf dtype")
    x=tf.linspace(-1,1,10)
    x=tf.cast(x,tf.float16)

print('dtype after ', x.dtype)

dtype returned :  <dtype: 'float64'>
'dtype' arg is tf.Variable can't be used to convert to other data type when the tensor already have its own specific tf dtype
dtype after  <dtype: 'float16'>


In [21]:
"""
However, since object like scaler: 5, array= [1,2,3] does not have specific tf dtype so it can directly be cast to any dtype. if we don't use dtype argument the Variable will have dtype according to given input. 
Example, 5 will have int32 dtype and 5.0 will have float32 dtype. 

"""

print('dtype :',tf.Variable(5).dtype)
print('dtype :',tf.Variable(5.0).dtype)
print('dtype :',tf.Variable(5,dtype=tf.float16).dtype)

try:
    print('dtype :',tf.Variable(5.0,dtype=tf.int32).dtype)
except:
    print('float dtype can not be converted to int dtype with dtype arg in tf.Variable')
   

dtype : <dtype: 'int32'>
dtype : <dtype: 'float32'>
dtype : <dtype: 'float16'>
float dtype can not be converted to int dtype with dtype arg in tf.Variable
