In [1]:
import tensorflow as tf 


*tf.reduce_*: Here _ can be replaced with other mathematical operation such as sum,max,mean, and so on. If the axis is not specified it will do the operation on each array shape of scaler and resulting tensor will be a 
reduced to scaler. However, if the axis is specified then then the operation will only take place at that axis and reduce the axis to 1.

In [7]:
# Reduce the shape to scaler when the axis is not mentioned
arr=tf.Variable([[1,2,3,4],
                 [4,5,6,7]])

print('tf.reduce_max :',tf.reduce_sum(arr))
print('tf.reduce_max :',tf.reduce_mean(arr))
print('tf.reduce_max :',tf.reduce_max(arr))

tf.reduce_max : tf.Tensor(32, shape=(), dtype=int32)
tf.reduce_max : tf.Tensor(4, shape=(), dtype=int32)
tf.reduce_max : tf.Tensor(7, shape=(), dtype=int32)


In [9]:
# performing on axis=1(on each columns). Then the new shape is same as axis 0 
arr=tf.Variable([[1,2,3,4],
                 [4,5,6,7]])

print('tf.reduce_max :',tf.reduce_sum(arr,axis=1))
print('tf.reduce_max :',tf.reduce_mean(arr,axis=1))
print('tf.reduce_max :',tf.reduce_max(arr,axis=1))

tf.reduce_max : tf.Tensor([10 22], shape=(2,), dtype=int32)
tf.reduce_max : tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.reduce_max : tf.Tensor([4 7], shape=(2,), dtype=int32)


In [10]:
# performing on axis=0(on each row). Then the new shape is same as axis  1. 
arr=tf.Variable([[1,2,3,4],
                 [4,5,6,7]])

print('tf.reduce_max :',tf.reduce_sum(arr,axis=0))
print('tf.reduce_max :',tf.reduce_mean(arr,axis=0))
print('tf.reduce_max :',tf.reduce_max(arr,axis=0))

tf.reduce_max : tf.Tensor([ 5  7  9 11], shape=(4,), dtype=int32)
tf.reduce_max : tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
tf.reduce_max : tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)


In [13]:
## performing reduce_ operation on 3 dimensional tensor

arr=tf.random.normal((10,20,35))
print('Original Shape :',arr.shape)
print('tf.reduce_max (axis not definied) :',tf.reduce_sum(arr).shape)
print('tf.reduce_max axis =0:',tf.reduce_mean(arr,axis=0).shape)
print('tf.reduce_max axis=1: ',tf.reduce_max(arr,axis=1).shape)
print('tf.reduce_max  axis=2: ',tf.reduce_max(arr,axis=2).shape)

Original Shape : (10, 20, 35)
tf.reduce_max (axis not definied) : ()
tf.reduce_max axis =0: (20, 35)
tf.reduce_max axis=1:  (10, 35)
tf.reduce_max  axis=2:  (10, 20)


*tf.equal(arr1,arr2 or scaler)*: if both arguments are array then thier shape must be equal. Check on each elements of array with the corresponding elements from another array

In [14]:
arr1=tf.Variable([1,2,3,4,0,9,8,0])
arr2=tf.Variable([1,12,13,44,0,89,8,0])
bool_arr1=tf.equal(arr1,arr2)
bool_arr2=tf.equal(arr1,0)

print('bool_arr1: ',bool_arr1)
print('bool_arr2: ',bool_arr2)

bool_arr1:  tf.Tensor([ True False False False  True False  True  True], shape=(8,), dtype=bool)
bool_arr2:  tf.Tensor([False False False False  True False False  True], shape=(8,), dtype=bool)
